spring:
  application:
    name: ManyToOneExample
    
  datasource:
    url: jdbc:mysql://localhost:3306/relationship
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 7777